# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{abingo}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wildfalcon"]
  s.date = %q{2010-08-06}
  s.description = %q{Incorperate AB Testing into your rails apps}
  s.email = %q{laurie@wildfalcon.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/abingo.rb",
     "lib/abingo/alternative.rb",
     "lib/abingo/controller/dashboard.rb",
     "lib/abingo/conversion_rate.rb",
     "lib/abingo/experiment.rb",
     "lib/abingo/rails/controller/dashboard.rb",
     "lib/abingo/statistics.rb",
     "lib/abingo/views/dashboard/_experiment.erb",
     "lib/abingo/views/dashboard/index.erb",
     "lib/abingo_sugar.rb",
     "lib/abingo_view_helper.rb",
     "strip.rb",
     "tasks/abingo_tasks.rake",
     "test/abingo_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/wildfalcon/abingo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A/B Testing for Rails}
  s.test_files = [
    "test/abingo_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

