# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{abingo-rails3}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrick McKenzie", "Wildfalcon", "Matthias Bauer"]
  s.date = %q{2010-12-20}
  s.description = %q{Rails A/B testing. One minute to install. One line to set up a new A/B test. One line to track conversion.}
  s.email = %q{moeffju@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "abingo-rails3.gemspec",
    "init.rb",
    "install.rb",
    "lib/abingo.rb",
    "lib/abingo/alternative.rb",
    "lib/abingo/controller/dashboard.rb",
    "lib/abingo/conversion_rate.rb",
    "lib/abingo/experiment.rb",
    "lib/abingo/rails/controller/dashboard.rb",
    "lib/abingo/railtie.rb",
    "lib/abingo/statistics.rb",
    "lib/abingo/views/ab_dashboard/_experiment.erb",
    "lib/abingo/views/ab_dashboard/index.erb",
    "lib/abingo_sugar.rb",
    "lib/abingo_view_helper.rb",
    "lib/generators/abingo_migration/USAGE",
    "lib/generators/abingo_migration/abingo_migration_generator.rb",
    "lib/generators/abingo_migration/templates/create_abingo_tables.rb",
    "lib/generators/abingo_views/USAGE",
    "lib/generators/abingo_views/abingo_views_generator.rb",
    "lib/generators/abingo_views/templates/views/ab_dashboard/_experiment.html.erb",
    "lib/generators/abingo_views/templates/views/ab_dashboard/index.html.erb",
    "strip.rb",
    "test/abingo_test.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{https://github.com/moeffju/abingo}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A/B Testing for Rails 3}
  s.test_files = [
    "test/abingo_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

